[package]
name = "ethernet"
version = "0.1.1"
edition = "2021"
description = "A parser for ethernet headers."
authors = ["Frostie314159"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Frostie314159/ethernet"

[dependencies]
ether-type = { path = "../ether-type", default-features = false }
mac-parser = { git = "https://github.com/Frostie314159/mac-parser.git" }
scroll = { git = "https://github.com/Frostie314159/scroll.git", branch = "fixed-array-impl", default-features = false }

[features]
alloc = []
default = ["alloc"]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "ethernet"
harness = false
